name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.0.6'

    - name: Upgrade Flutter
      run: flutter upgrade

    - name: Clean Flutter Project
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get

    - name: Build release APK
      run: flutter build apk --release --verbose

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
