name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0' # 更新到 Flutter 3.0.0 以包含 Dart 2.18.6

    - name: Install dependencies
      run: |
        flutter pub get
        flutter doctor -v

    - name: Run tests
      run: flutter test

    - name: Build application
      run: flutter build apk
